### ISSUE TITLE
Testing needed for actuator methods

### ISSUE THREAD

**Issue by JrtPec** [EnergyID/smappy#2]
The actuator methods have been implemented, but I don't have a Smappee set-up with actuators to test on. If there is somebody out there who could test it for me, please let me know.

**Comment by serge-b** [comment]
Hi there,
I tried the actuator, i get an HTTP 500 response.
Can't find where the issue is. I did implement this in javascript, it worked just fine...
https://github.com/serge-b/Smabble

**Comment by serge-b** [comment]
Nailed it!
when making a POST request, if the paylod is json, you need to replace data=data by json=data
`r = requests.post(url, headers=headers, json=data)`

It works now!

**Comment by JrtPec** [comment]
Great!

I have changed the code and pushed a new version to pip. Could you check it out and confirm that it works? Maybe than I can close this issue.

Thanks for contributing!
