### ISSUE TITLE
HowTo smappee with smappy & python

### ISSUE THREAD

**Issue by stefferber** [EnergyID/smappy#5]
@JrtPec thanks a lot for sharing your great design and implementation of the smappee REST API including the OAuth2 refresh token issue!  Your software worked right away for me but I had a lot of trouble setting up the basics behind. As a beginner with Python and OAuth2 I like to share with you how I got all the bits and pieces together.

# Overview of steps

1. Buy and install smappe – the device to measure your electrical power consumption
2. Get the client id and client secret by eMail from support@smappee.com
3. Install python3
4. Install smappy package with pip3
5. Run a test Python script

## 1. Buy and install shape
Once your [smappee device](http://www.smappee.com) is installed and online connected to the smappee server (currently running on AWS) you can access the data from the server (and not from the gateway) via this [REST APIs](https://smappee.atlassian.net/wiki/display/DEVAPI/SmappeeDevAPI+Home). If you want to access the smappee gateway in your local network [directly please check out this](https://github.com/mortenf/smappee-tools) 

## 2. Get the client id and client secret 
In order to access the REST APIs you need 4 things
a) your smappee **user name** from your smappee app (iOS or Android)
b) your smappee **user password** from your smappee app
c) **client id** for identifiying the origin of your API calls at the smappee server  
d) **client secret** for initially getting an access token from the smappee server via OAuth2

a) and b) are under your own control from the set-up of smappee. Wheras c) and d) you receive by (unencrypted!) eMail from support@smappee.com
  
## 3. Install python3
Get your distribution from [python.org](https://www.python.org/downloads/) and install…

## 4. Install smappy package with pip3
As a phyton beginner, all the troubles of Mac OS using python 2.7, cloning the git hub repository, missing access rights to install the package this took me a few hours (and a screwed up python installation) to get right. In the end it was as simple as that:

`sudo pip3 install snappy`

on Mac as it needs to be installed in the pyhton3  ( in my case `/Library/Frameworks/Python.framework/Versions/3.5/`). You might need to use

`sudo pip install snappy`

## 5. Run a test Python script
start Python3 from your shell and enter line by line the following commands. You have to **replace client id, client secrect, user name, user password with yours**:

```python
$ python3
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 26 2016, 10:47:25) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from smappy.smappy import Smappee, SimpleSmappee
>>> s = Smappee("client id", "client secret")
>>> s.authenticate("user name", "user password")
>>> service_location_id = s.get_service_locations()['serviceLocations'][0]['serviceLocationId']
>>> print ("id: ", service_location_id)
id:  314

```
In this case the authorization worked if you get a valid service_location_ID. I have picked the first smappee device in the service location list. This data type is a bit tricky.  get_service_locations returns a "DICT" of "LIST" of location in a "DICT". You can parse through if you print the results

```python
>>> s.get_service_locations()
{'appName': 'MyFirstApp', 'serviceLocations': [{'name': 'Home', 'serviceLocationId': 314}]}
```

If you have multiple smappee devices you have to use the right index instead of [0].

An now we can get data

```python
>>> s.get_consumption(service_location_id, 1475309600000, 1475527028000, 3)
{'consumptions': [{'solar': 0.0, 'consumption': 2183.0, 'alwaysOn': 15264.0, 'timestamp': 1475359200000}, {'solar': 0.0, 'consumption': 3970.4, 'alwaysOn': 15131.0, 'timestamp': 1475445600000}], 'serviceLocationId': 314}
```

In order to change the start and end time of data query you have to convert human readable time to unix time stamps. I do this via [epoch converter](http://www.epochconverter.com)   
Of course python has timestamp function itself. Here we return the date from the last week:

```python
>>> from datetime import datetime, timedelta
>>> from calendar import timegm
>>> end_time = datetime.utcnow()
>>> start_time = end_time - timedelta(weeks=1, days=0, hours=0, minutes=0, seconds=00)
>>> start = 1000 * timegm(start_time.utctimetuple())
>>> end   = 1000 * timegm(end_time.utctimetuple())
>>> s.get_consumption(service_location_id, start, end, 3)
{'consumptions': [{'solar': 0.0, 'consumption': 3970.4, 'alwaysOn': 15131.0, 'timestamp': 1475445600000}, 
{'solar': 0.0, 'consumption': 12245.3, 'alwaysOn': 14976.0, 'timestamp': 1475532000000}, 
{'solar': 0.0, 'consumption': 12717.7, 'alwaysOn': 15288.0, 'timestamp': 1475618400000}, 
{'solar': 0.0, 'consumption': 6538.7, 'alwaysOn': 18818.0, 'timestamp': 1475704800000},
{'solar': 0.0, 'consumption': 10552.6, 'alwaysOn': 20552.0, 'timestamp': 1475791200000}, 
{'solar': 0.0, 'consumption': 7814.7, 'alwaysOn': 21457.0, 'timestamp': 1475877600000}, 
{'solar': 0.0, 'consumption': 7101.0, 'alwaysOn': 17550.0, 'timestamp': 1475964000000}], 'serviceLocationId': 314} 

```
Now you can start your real project…

**Comment by JrtPec** [comment]
Wow, thanks for the great write-up! This is great material to put on the wiki, I'll certainly put it on there!

I'll also piggy-back onto what you wrote and write something about the `get_consumption_dataframe` method. It returns your consumption as a Pandas DataFrame. If you don't know what that is yet, I would certainly recommend it: it basically is an array wrapper, which has slicing, indexing, resampling, interpolating, plotting, statistics, plotting, IO from/to CSV, Excel, ... basically anything you need if you want to do some data analysis!

**Comment by JrtPec** [comment]
Everything was added to the wiki

**Comment by stefferber** [comment]
Looks great. I will explore Pandas during my next programming weekend....

**Comment by BugRaptor** [comment]
I'm a bit confused with the Smappee API. How to get the current power of the Solar production. (Like displayed on the main screen of the Smappee Smartphone App) ?
